### ISSUE TITLE
Lights in 32 bits

### ISSUE THREAD

**Issue by on4r4p** [captnfab/PianoBooster#284]
Hello Im looking for a way to make my casio keyboard to light up with pianobooster but in 32 bits .
So do you think i could just take the part that manage lights from the 64 bits version and put it in the 32 bits?
Edit: Wow so ..the version im using is 0.6.4 and it was released in 2009  So i guess just by the look at the code that its going to be a little bit more difficult than just a simple copy past ..
Im gonna try to build 0.6.5 cause it's seems this feature was introduced in this version.

**Comment by louis-barman** [comment]
Hi @on4r4p,

I am guessing you have on old PC and are running Windows ---  the current Windows `PianoBoosterInstall-SF-1.0.0.exe` build is a actually 32 build. I think that you have hit the issue raised in this thread. http://piano-booster.2625608.n2.nabble.com/Menu-bar-is-not-visible-td7572894.html. The issue with older PC is probably caused when the source code was upgraded from QT 4 to QT5 and the QGLWidget Class was made obsolete.  It is probably best you post your reply to  http://piano-booster.2625608.n2.nabble.com/Menu-bar-is-not-visible-td7572894.html. 

There is also some discussion about the piano keyboard lights bug fix in this thread. http://piano-booster.2625608.n2.nabble.com/quot-Smarter-quot-Lights-on-Yamaha-EZ-200-td7572533.html#a7572815

**Comment by on4r4p** [comment]
Im on Linux , on many linux ..
But sadly i cannot run pianobooster on my others computers cause (longstoryshort)
they are cursed by Nvidia and i can't get any midi input or output to work with pianobooster.
Anyway i m still trying to build 0.6.5 but there are a lot of errors and if i can't solve them
i will definitely try the windows 32 built you told me about .
Maybe it will work with wine ..

**Comment by louis-barman** [comment]
Ok please can your try compiling this branch `wip/opengl` that I have just pushed. Please see: https://github.com/pianobooster/PianoBooster/tree/wip/opengl As that I am hoping it will solve the issues with your old graphics card. I am hoping that old graphics cards that worked under PB 0.6.5 / QT4 will now work with PB  and QT 5.

Please can you report back with the logs  for both the current `develop` branch and the  new  `wip/opengl`  branch. Did you see a "renderText is not supported under OpenGL" message.

Regarding the MIDI output, can you see you midi device using this command `aplaymidi -l` ??  I suspect you have a hardware issue with your MIDI. There have been no significant MIDI changes between PB  0.6.5 and  1.0.1

**Comment by on4r4p** [comment]
Im sorry i was not being able to build wip/opengl nor from develop both end up with this error.

`build/CMakeFiles/pianobooster.dir/build.make:62 : la recette pour la cible « build/CMakeFiles/pianobooster.dir/QtMain.o » a échouée
make[2]: *** [build/CMakeFiles/pianobooster.dir/QtMain.o] Erreur 1
CMakeFiles/Makefile2:88 : la recette pour la cible « build/CMakeFiles/pianobooster.dir/all » a échouée
make[1]: *** [build/CMakeFiles/pianobooster.dir/all] Erreur 2
Makefile:127 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2`

sidestory:
aplaymidi -l worked on most of my computers but not with the one using nvidia proprietary driver .
its an old one (nvidia340) and i had to modify it to make it work so yeah i think it's related .
Pianobooster windows version worked with wine and my Keyboard has been detected successfully
but still can't turn the lights on and off on my casio .

**Comment by louis-barman** [comment]
Ok I was not expecting the Windows exe to work on wine but I am glad that it does. I cannot tell wiil went wrong from that short log message you posted above. For me to investigate it further I would need the complete log. (delete everything in the build directory and then log all the output from the `cmake ..` command and the the `make` command and then zip the build directory and post here) 

to get the keyboards lights working start pianobooster use the `pianobooster --lights` flag on the command line. If you get problems with the keyboard lights please post to the user forum.

**Comment by on4r4p** [comment]
ok thnks for your time :)
I though those previous errors were not important but here the full output :
(changed my user name to $USER)

```
git clone --single-branch --branch wip/opengl https://github.com/pianobooster/PianoBooster.git

remote: Enumerating objects: 58, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 10074 (delta 24), reused 31 (delta 12), pack-reused 10016
Réception d'objets: 100% (10074/10074), 9.09 MiB | 2.14 MiB/s, fait.
Résolution des deltas: 100% (8042/8042), fait.
Vérification de la connectivité... fait.

cd PianoBooster/

cmake .

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
PREFIX: /usr/local
DATA_DIR: share/games/pianobooster
CMAKE_INSTALL_BINDIR: bin
-- Found OpenGL: /usr/lib/i386-linux-gnu/libGL.so  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'ftgl'
--   Found ftgl, version 2.1.3~rc5
-- Checking for module 'fluidsynth'
--   Found fluidsynth, version 1.1.6
Building with internal fluidsynth
-- Checking for module 'rtmidi'
--   Found rtmidi, version 2.1.0
Please consider to switch to CMake 3.13.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/$USER/Documents/PianoBooster/PianoBooster

make

Scanning dependencies of target pianobooster_automoc
[  1%] Automatic moc, uic and rcc for target pianobooster
Generating ui_GuiKeyboardSetupDialog.h
Generating ui_GuiLoopingPopup.h
Generating ui_GuiMidiSetupDialog.h
Generating ui_GuiPreferencesDialog.h
Generating ui_GuiSidePanel.h
Generating ui_GuiSongDetailsDialog.h
Generating ui_GuiTopBar.h
Generating moc_Draw.cpp
Generating moc_GlView.cpp
Generating moc_GuiKeyboardSetupDialog.cpp
Generating moc_GuiLoopingPopup.cpp
Generating moc_GuiMidiSetupDialog.cpp
Generating moc_GuiPreferencesDialog.cpp
Generating moc_GuiSidePanel.cpp
Generating moc_GuiSongDetailsDialog.cpp
Generating moc_GuiTopBar.cpp
Generating moc_QtWindow.cpp
Generating moc_Settings.cpp
Generating moc_TrackList.cpp
[  1%] Built target pianobooster_automoc
Scanning dependencies of target pianobooster
[  3%] Building CXX object build/CMakeFiles/pianobooster.dir/QtMain.o
In file included from /home/$USER/Documents/PianoBooster/PianoBooster/src/MidiDevice.h:40:0,
                 from /home/$USER/Documents/PianoBooster/PianoBooster/src/Conductor.h:34,
                 from /home/$USER/Documents/PianoBooster/PianoBooster/src/Song.h:35,
                 from /home/$USER/Documents/PianoBooster/PianoBooster/src/QtWindow.h:32,
                 from /home/$USER/Documents/PianoBooster/PianoBooster/src/QtMain.cpp:36:
/home/$USER/Documents/PianoBooster/PianoBooster/src/MidiDeviceBase.h:70:5: warning: identifier ‘nullptr’ is a keyword in C++11 [-Wc++0x-compat]
     QSettings* qsettings = nullptr;
     ^
/home/$USER/Documents/PianoBooster/PianoBooster/src/MidiDeviceBase.h:70:28: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
     QSettings* qsettings = nullptr;
                            ^
/home/$USER/Documents/PianoBooster/PianoBooster/src/MidiDeviceBase.h:70:28: error: ‘nullptr’ was not declared in this scope
In file included from /home/$USER/Documents/PianoBooster/PianoBooster/src/Song.h:36:0,
                 from /home/$USER/Documents/PianoBooster/PianoBooster/src/QtWindow.h:32,
                 from /home/$USER/Documents/PianoBooster/PianoBooster/src/QtMain.cpp:36:
/home/$USER/Documents/PianoBooster/PianoBooster/src/TrackList.h:132:23: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
     int m_noteCount = 0;
                       ^
/home/$USER/Documents/PianoBooster/PianoBooster/src/TrackList.h:133:25: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
     int m_firstPatch = -1;
                         ^
/home/$USER/Documents/PianoBooster/PianoBooster/src/TrackList.h:134:31: error: ‘>>’ should be ‘> >’ within a nested template argument list
     QVector<QSharedPointer<int>> m_noteFrequencyByTrack;
                               ^
In file included from /home/$USER/Documents/PianoBooster/PianoBooster/src/Scroll.h:32:0,
                 from /home/$USER/Documents/PianoBooster/PianoBooster/src/Score.h:32,
                 from /home/$USER/Documents/PianoBooster/PianoBooster/src/QtWindow.h:33,
                 from /home/$USER/Documents/PianoBooster/PianoBooster/src/QtMain.cpp:36:
/home/$USER/Documents/PianoBooster/PianoBooster/src/Draw.h: In destructor ‘virtual CDraw::~CDraw()’:
/home/$USER/Documents/PianoBooster/PianoBooster/src/Draw.h:80:19: error: ‘nullptr’ was not declared in this scope
         if (font!=nullptr) delete font;
                   ^
In file included from /home/$USER/Documents/PianoBooster/PianoBooster/src/Piano.h:34:0,
                 from /home/$USER/Documents/PianoBooster/PianoBooster/src/Score.h:33,
                 from /home/$USER/Documents/PianoBooster/PianoBooster/src/QtWindow.h:33,
                 from /home/$USER/Documents/PianoBooster/PianoBooster/src/QtMain.cpp:36:
/home/$USER/Documents/PianoBooster/PianoBooster/src/Settings.h: At global scope:
/home/$USER/Documents/PianoBooster/PianoBooster/src/Settings.h:209:53: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
     QStringList m_fluidSoundFontNames = QStringList();
                                                     ^
In file included from /home/$USER/Documents/PianoBooster/PianoBooster/src/QtWindow.h:36:0,
                 from /home/$USER/Documents/PianoBooster/PianoBooster/src/QtMain.cpp:36:
/home/$USER/Documents/PianoBooster/PianoBooster/src/GuiSidePanel.h:181:39: error: ‘>>’ should be ‘> >’ within a nested template argument list
     QMap<QWidget*,QMap<QString,QString>> listWidgetsRetranslateUi;
                                       ^
/home/$USER/Documents/PianoBooster/PianoBooster/src/GuiSidePanel.h:182:39: error: ‘>>’ should be ‘> >’ within a nested template argument list
     QMap<QAction*,QMap<QString,QString>> listActionsRetranslateUi;
                                       ^
In file included from /home/$USER/Documents/PianoBooster/PianoBooster/src/QtWindow.h:37:0,
                 from /home/$USER/Documents/PianoBooster/PianoBooster/src/QtMain.cpp:36:
/home/$USER/Documents/PianoBooster/PianoBooster/src/GuiTopBar.h:84:39: error: ‘>>’ should be ‘> >’ within a nested template argument list
     QMap<QWidget*,QMap<QString,QString>> listWidgetsRetranslateUi;
                                       ^
/home/$USER/Documents/PianoBooster/PianoBooster/src/GuiTopBar.h:85:39: error: ‘>>’ should be ‘> >’ within a nested template argument list
     QMap<QAction*,QMap<QString,QString>> listActionsRetranslateUi;
                                       ^
In file included from /home/$USER/Documents/PianoBooster/PianoBooster/src/QtMain.cpp:36:0:
/home/$USER/Documents/PianoBooster/PianoBooster/src/QtWindow.h:202:39: error: ‘>>’ should be ‘> >’ within a nested template argument list
     QMap<QWidget*,QMap<QString,QString>> listWidgetsRetranslateUi;
                                       ^
/home/$USER/Documents/PianoBooster/PianoBooster/src/QtWindow.h:203:39: error: ‘>>’ should be ‘> >’ within a nested template argument list
     QMap<QAction*,QMap<QString,QString>> listActionsRetranslateUi;
                                       ^
/home/$USER/Documents/PianoBooster/PianoBooster/src/QtMain.cpp: In function ‘int main(int, char**)’:
/home/$USER/Documents/PianoBooster/PianoBooster/src/QtMain.cpp:48:26: warning: range-based ‘for’ loops only available with -std=c++11 or -std=gnu++11
         for (QString arg:argList){
                          ^
/home/$USER/Documents/PianoBooster/PianoBooster/src/QtMain.cpp:59:34: error: ‘nullptr’ was not declared in this scope
         QMessageBox::information(nullptr, QMessageBox::tr("OpenGL support"),
                                  ^
build/CMakeFiles/pianobooster.dir/build.make:62 : la recette pour la cible « build/CMakeFiles/pianobooster.dir/QtMain.o » a échouée
make[2]: *** [build/CMakeFiles/pianobooster.dir/QtMain.o] Erreur 1
CMakeFiles/Makefile2:88 : la recette pour la cible « build/CMakeFiles/pianobooster.dir/all » a échouée
make[1]: *** [build/CMakeFiles/pianobooster.dir/all] Erreur 2
Makefile:127 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
```

**Comment by louis-barman** [comment]
OK what OS are you running? It looks like a very old version. The problem is cause by you using gcc g++ 5.4.0 I have tested on my oldest system and it compiles fine using both  g++ 5.4 and gcc g++ 7.x. So you can either upgrade to a new compiler or fix the errors by reverting to use older gcc code.

However since it works for you using wine I recommend that you use that. Remember to use the --lights flag when start PB from the command line.

**Comment by on4r4p** [comment]
> "OK what OS are you running? It looks like a very old version."

Hummm ........no ? (lying)

Anyway ^ ^

Its working now iv being able to successfully build and compile wip/opengl by upgrading gcc/g++ and using :
`cmake  -DUSE_BUNDLED_RTMIDI=ON`

And you know what ?
Lights are working beautifully  !

Many Thanks Louis and long live to Pianobooster :+1:

**Comment by louis-barman** [comment]
Good. Also please can I get you @on4r4p  to test the AppImage for the `wip/opengl` branch on your antique OS. It should be available here: https://github.com/pianobooster/PianoBooster/actions/runs/595659418 and https://github.com/pianobooster/PianoBooster/suites/2112354659/artifacts/42996375

You can only see the download if you are logged into GitHub

It would be helpful if you would know OS you are running incase other hit the same problem.  Thanks
